# Generated by Django 3.2.6 on 2021-08-30 23:32

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('administrador', '0002_auto_20210824_1558'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=40, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, max_length=255, verbose_name='Descripcion')),
                ('date_event_start', models.DateTimeField(default=datetime.datetime(2021, 8, 30, 20, 32, 11, 767763), verbose_name='Fecha de alta del evento')),
                ('date_event_end', models.DateTimeField(default=datetime.datetime(2021, 8, 30, 20, 32, 11, 767763), verbose_name='Fecha de baja del evento')),
                ('location', models.CharField(blank=True, max_length=255, verbose_name='Ubicación')),
                ('event_link', models.URLField(verbose_name='Link')),
                ('state', models.CharField(choices=[('activo', 'ACTIVO'), ('inactivo', 'INACTIVO'), ('oculto', 'OCULTO'), ('suspendido', 'SUSPENDIDO')], max_length=10, null=True, verbose_name='Estado')),
                ('max_guests', models.IntegerField(verbose_name='Capacidad máxima de invitados')),
                ('visibility', models.CharField(choices=[('publico', 'PUBLICO '), ('privado', 'PRIVADO'), ('solo_link', 'SOLO CON LINK')], max_length=14, verbose_name='Visibilidad')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Organizador')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
            },
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
        migrations.AddField(
            model_name='userprofile',
            name='date_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='date_start',
            field=models.DateTimeField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='state',
            field=models.CharField(choices=[('activo', 'ACTIVO'), ('inactivo', 'INACTIVO'), ('oculto', 'OCULTO'), ('suspendido', 'SUSPENDIDO')], max_length=10, null=True, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='key_expires',
            field=models.DateTimeField(default=datetime.date.today),
        ),
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted_event', models.BooleanField(default=False, verbose_name='Aceptado')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrador.event', verbose_name='Evento')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Integrate')),
            ],
            options={
                'verbose_name': 'Invitacion',
                'verbose_name_plural': 'Invitaciones',
            },
        ),
    ]
