# Generated by Django 3.2.6 on 2021-08-31 16:29

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0003_auto_20210830_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date_event_end',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 31, 13, 29, 53, 856582), verbose_name='Fecha de baja del evento'),
        ),
        migrations.AlterField(
            model_name='event',
            name='date_event_start',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 31, 13, 29, 53, 856582), verbose_name='Fecha de alta del evento'),
        ),
        migrations.AlterField(
            model_name='event',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrador.userprofile', verbose_name='Organizador'),
        ),
    ]
