# Generated by Django 3.2.6 on 2021-09-28 18:41

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('administrador', '0007_auto_20210901_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date_event_end',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 28, 18, 41, 42, 613405), verbose_name='Fecha de baja del evento'),
        ),
        migrations.AlterField(
            model_name='event',
            name='date_event_start',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 28, 18, 41, 42, 613386), verbose_name='Fecha de alta del evento'),
        ),
        migrations.AlterField(
            model_name='event',
            name='state',
            field=models.CharField(choices=[('activo', 'ACTIVO'), ('oculto', 'OCULTO')], max_length=10, null=True, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='event',
            name='visibility',
            field=models.CharField(choices=[('publico', 'PÚBLICO '), ('privado', 'PRIVADO')], max_length=14, verbose_name='Visibilidad'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='state',
            field=models.CharField(choices=[('activo', 'ACTIVO'), ('finalizado', 'FINALIZADO'), ('oculto', 'OCULTO'), ('suspendido', 'SUSPENDIDO')], max_length=10, null=True, verbose_name='Estado'),
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Titulo')),
                ('description', models.CharField(max_length=255, verbose_name='Descripcion')),
                ('status', models.CharField(choices=[('realizada', 'REALIZADA'), ('porhacer', 'POR HACER'), ('enprogreso', 'EN PROGRESO')], max_length=11, verbose_name='Estado de la tarea')),
                ('cost', models.FloatField(default=0)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrador.event', verbose_name='Evento')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Encargado')),
            ],
            options={
                'verbose_name': 'Tarea',
                'verbose_name_plural': 'Tareas',
            },
        ),
    ]
