# Generated by Django 3.2.6 on 2021-09-28 19:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0011_auto_20210928_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date_event_end',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 28, 16, 42, 29, 671922), verbose_name='Fecha de baja del evento'),
        ),
        migrations.AlterField(
            model_name='event',
            name='date_event_start',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 28, 16, 42, 29, 671922), verbose_name='Fecha de alta del evento'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('realizada', 'REALIZADA'), ('porhacerasignada', 'POR HACER ASIGNADA'), ('enprogreso', 'EN PROGRESO'), ('porhacerNOasignada', 'POR HACER NO ASIGNADA')], max_length=22, verbose_name='Estado de la tarea'),
        ),
    ]
