# Generated by Django 3.2.6 on 2021-10-05 23:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0012_auto_20210928_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date_event_end',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 5, 20, 41, 9, 991618), verbose_name='Fecha de baja del evento'),
        ),
        migrations.AlterField(
            model_name='event',
            name='date_event_start',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 5, 20, 41, 9, 991618), verbose_name='Fecha de alta del evento'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('REALIZADA', 'REALIZADA'), ('POR HACER ASIGNADA', 'POR HACER ASIGNADA'), ('EN PROGRESO', 'EN PROGRESO'), ('POR HACER NO ASIGNADA', 'POR HACER NO ASIGNADA')], max_length=22, verbose_name='Estado de la tarea'),
        ),
    ]
