# Generated by Django 3.2.6 on 2021-10-12 04:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0015_auto_20211012_0429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date_event_end',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 12, 4, 32, 18, 666317), verbose_name='Fecha de baja del evento'),
        ),
        migrations.AlterField(
            model_name='event',
            name='date_event_start',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 12, 4, 32, 18, 666285), verbose_name='Fecha de alta del evento'),
        ),
    ]
