# Generated by Django 3.2.6 on 2021-10-12 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0003_alter_userprofile_key_expires'),
        ('administrador', '0016_auto_20211012_0432'),
    ]

    operations = [
    ]
