# Generated by Django 3.2.6 on 2021-10-15 21:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0018_auto_20211012_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date_event_end',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 15, 21, 59, 58, 129560), verbose_name='Fecha de baja del evento'),
        ),
        migrations.AlterField(
            model_name='event',
            name='date_event_start',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 15, 21, 59, 58, 129516), verbose_name='Fecha de alta del evento'),
        ),
    ]
