# Generated by Django 3.2.6 on 2021-10-23 16:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0019_auto_20211015_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date_event_end',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 23, 16, 39, 1, 752875), verbose_name='Fecha de baja del evento'),
        ),
        migrations.AlterField(
            model_name='event',
            name='date_event_start',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 23, 16, 39, 1, 752846), verbose_name='Fecha de alta del evento'),
        ),
    ]
