# Generated by Django 3.2.6 on 2021-10-23 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0019_auto_20211012_1831'),
        ('administrador', '0020_auto_20211023_1639'),
    ]

    operations = [
    ]
