# Generated by Django 3.2.6 on 2021-10-24 22:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0021_merge_0019_auto_20211012_1831_0020_auto_20211023_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date_event_end',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 24, 19, 32, 51, 922958), verbose_name='Fecha de baja del evento'),
        ),
        migrations.AlterField(
            model_name='event',
            name='date_event_start',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 24, 19, 32, 51, 922958), verbose_name='Fecha de alta del evento'),
        ),
        migrations.AlterField(
            model_name='event',
            name='state',
            field=models.CharField(choices=[('activo', 'ACTIVO'), ('finalizado', 'FINALIZADO'), ('oculto', 'OCULTO'), ('suspendido', 'SUSPENDIDO')], max_length=10, null=True, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='state',
            field=models.CharField(choices=[('activo', 'ACTIVO'), ('baneado', 'BANEADO')], max_length=10, null=True, verbose_name='Estado'),
        ),
    ]
