# Generated by Django 3.2.6 on 2021-10-24 22:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0022_auto_20211024_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date_event_end',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 24, 19, 49, 58, 57672), verbose_name='Fecha de baja del evento'),
        ),
        migrations.AlterField(
            model_name='event',
            name='date_event_start',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 24, 19, 49, 58, 57672), verbose_name='Fecha de alta del evento'),
        ),
    ]
