# Generated by Django 3.2.6 on 2021-11-03 00:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0023_auto_20211024_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date_event_end',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 2, 21, 12, 31, 863624), verbose_name='Fecha de baja del evento'),
        ),
        migrations.AlterField(
            model_name='event',
            name='date_event_start',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 2, 21, 12, 31, 863624), verbose_name='Fecha de alta del evento'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_link',
            field=models.CharField(max_length=200, verbose_name='Link'),
        ),
    ]
